services:
  catalogdb:
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # removed healthcheck (some mongo images don't include the mongo client)
  catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ASPNETCORE_URLS=http://+:8080"
      - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
      - "DatabaseSettings__DatabaseName=CatalogDb"
      - "DatabaseSettings__ProductCollectionName=Products"
      - "DatabaseSettings__BrandCollectionName=Brands"
      - "DatabaseSettings__TypeCollectionName=Types"
    depends_on:
      - catalogdb          
    ports:
      - "8000:8080"